### ISSUE TITLE
Android 飞书兼容性

### ISSUE THREAD

**Issue by wangrunlin** [Darmau/firewood-svelte#2]
https://github.com/Darmau/firewood-svelte/assets/64216877/3d5e539b-3e92-4257-b86b-5e27ec1ce5fd

在飞书中点击导航栏按钮无反应，并且首页导航栏文字五间距。

设备型号: OPPO K3

**Comment by darmau** [comment]
看起来应该是没加载完。虽然还没被gfw正式认证，但在有些地区会出现访问慢甚至被官方认定为诈骗网站的情况。通过代理应该就没问题
